import Head from "next/head";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/Components/Header";
import shijinbenny_hero from "../../public/shijinBenny_hero.png";
import exp from "../../public/exp.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowDown, faArrowDown19, faGear } from "@fortawesome/free-solid-svg-icons";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [styleSwitch, setStyleSwitch] = useState(false);
  const [theme, setTheme] = useState("#D8BA1B");
  const handleSwitchColor = (color) => {
    setTheme(color);
  };
  const handleSwitch = () => {
    setStyleSwitch((state) => !state);
    console.log(styleSwitch);
    if (styleSwitch === true) {
      document.getElementById("switchWrapper").style.right = "0px";
    } else {
      document.getElementById("switchWrapper").style.right = "-250px";
    }
  };
  return (
    <>
      <Head>
        <title>SHIJIN BENNY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900"
          type="text/css"
        />
      </Head>
      <header className={styles.headerOuter}>
        <Header />
      </header>
      <main className={styles.main}>
        {/* Intro ===================================>*/}
        <section className={styles.heroOuter} style={{ backgroundColor: `${theme}` }}>
          <div className={styles.HeroInner}>
            <div className={styles.heroleft}>
              <h1>Hi, I'm SHIJIN BENNY</h1>
              <h2>DEVELOPER</h2>
              <p>based in kerala,India</p>
              <button>CONTACT ME</button>
            </div>
            <div className={styles.heroright}>
              <img src={shijinbenny_hero.src} alt="" />
            </div>
          </div>
          <span className={styles.downArrow}>
            <FontAwesomeIcon icon={faArrowDown} height={32} />
          </span>
        </section>

        <section className={styles.AboutOuter}>
          <div className={styles.AboutInner}>
            <p className={styles.header1} style={{ backgroundColor: `${theme}` }}>
              About me
            </p>
            <h2 className={styles.header2}>Know Me More</h2>
            <div className={styles.aboutUsContentWrapper}>
              <div className={styles.left}>
                <h2 className={styles.header3}>
                  Hi, I'm <span style={{ textDecorationColor: `${theme}` }}>Shijin Benny</span>
                </h2>
                <p className={styles.aboutmeText}>
                  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident, et! Blanditiis ad dolore maiores
                  odit sunt voluptas reprehenderit vitae consequuntur voluptatum. A dolor tenetur exercitationem sit
                  distinctio ad molestias temporibus?Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Perspiciatis ducimus veritatis libero omnis doloremque laboriosam similique alias assumenda odit culpa
                  fugit, excepturi nam? Tempore ratione earum cupiditate, reiciendis modi illum?
                </p>
              </div>
              <div className={styles.right}>
                <div className={styles.expCirlce} style={{ backgroundColor: `${theme}` }}>
                  <span>1</span>
                </div>
                <h3 className={styles.expText}>
                  Year of <span>Experience</span>
                </h3>
              </div>
            </div>
            <div className={styles.infoContainer}>
              <div className={styles.infoDiv}>
                <p>Name</p>
                <p>SHIJIN BENNY</p>
              </div>
              <div className={styles.infoDiv}>
                <p>Email</p>
                <p>shijinbenny008@gmail.com</p>
              </div>
              <div className={styles.infoDiv}>
                <p>Date of birth</p>
                <p>10 December 1999</p>
              </div>
              <div className={styles.infoDiv}>
                <p>From</p>
                <p>Palakkad, Kerala,India</p>
              </div>
            </div>
          </div>
        </section>

        <div className={styles.StyleSwitch_Wrapper} id="switchWrapper">
          <div className={styles.left} onClick={handleSwitch}>
            <FontAwesomeIcon icon={faGear} color="#fff" height={20} />
          </div>
          <div className={styles.right}>
            <p>Color Switcher</p>
            <div className={styles.colorWrapper}>
              <div style={{ backgroundColor: "#D8BA1B" }} onClick={() => handleSwitchColor("#D8BA1B")}></div>
              <div style={{ backgroundColor: "#1B7DD8" }} onClick={() => handleSwitchColor("#1B7DD8")}></div>
              <div style={{ backgroundColor: "#1BD8B6" }} onClick={() => handleSwitchColor("#1BD8B6")}></div>
              <div style={{ backgroundColor: "#1BD867" }} onClick={() => handleSwitchColor("#1BD867")}></div>
            </div>
            <div className={styles.colorWrapper}>
              <div style={{ backgroundColor: "#D85F1B" }} onClick={() => handleSwitchColor("#D85F1B")}></div>
              <div style={{ backgroundColor: "#BDD81B" }} onClick={() => handleSwitchColor("#BDD81B")}></div>
              <div style={{ backgroundColor: "#F4C091" }} onClick={() => handleSwitchColor("#F4C091")}></div>
              <div style={{ backgroundColor: "#91A1F4" }} onClick={() => handleSwitchColor("#91A1F4")}></div>
            </div>
          </div>
        </div>
        {/* End */}
      </main>
    </>
  );
}
